engine_settings:
  time_scale: 1.02
  quality_level: 5
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: False
  width: 84
  height: 84
checkpoint_settings:
    run_id: mlady
    load_model: False
    resume: False
    force: False
    train_model: False
    inference: False
    results_dir: Assets/ML-Agents/Results
torch_settings:
      device: cuda
debug: False
